name: Run Test and Code Coverage

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test-and-code-coverage:
    run-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Depedencies
        run: yarn install

      - name: Run Test
        run: yarn test

      - name: Run Code Coverage
        run: yarn cov

      - name: Commit and Push Changes
        run: |
          git config --local user.email "codecov.actions@github.com"
          git config --local user.name "Codecov"
          git add README.md
          git commit -m "Update codecov badge"
          git push


